-- Bike_Store_Sales_And_Inventory_Analysis_2 

-- Project Overview 
-- This project focuses strictly on relational logic using JOINs and aggregation functions. 
-- Subqueries and CTEs are intentionally excluded to strengthen core SQL fundamentals.

-- Problem Statement: 
-- Analyze store performance and inventory levels for a bicycle retail chain.


-- Create the Database 
CREATE DATABASE BikeStoreProject_2; 


-- use the database
USE BikeStoreProject_2;


-- imported table show any one
SELECT * FROM customers;


-- imported table show the data
SELECT * FROM orders;


-- imported table show the data
SELECT * FROM brands;



-- 1. Store Performance – Total revenue generated by each store.
SELECT 
s.store_name,
SUM(i.quantity * i.list_price *(1 - i.discount)) AS total_revenue
FROM order_items AS i
JOIN orders AS o
ON i.order_id = o.order_id
JOIN stores AS s
ON s.store_id = o.store_id
GROUP BY s.store_name
ORDER BY total_revenue DESC;



-- 1. Store Performance – Total revenue generated by each store.
SELECT 
s.store_name,
SUM(i.quantity * i.list_price *(1 - i.discount)) AS total_revenue
FROM stores AS s
JOIN orders AS o
ON s.store_id = o.store_id
JOIN order_items AS i
ON i.order_id = o.order_id
GROUP BY s.store_name                       
ORDER BY total_revenue DESC;


-- 2. Product Popularity – Top 5 most sold products by quantity. 
SELECT 
p.product_name ,
i.quantity,
o.order_status
FROM products AS p
JOIN order_items AS i
ON p.product_id = i.product_id
JOIN orders AS O
ON o.order_id = i.order_id
ORDER BY i.quantity DESC
LIMIT 5;


-- 3. Customer Location – Customers who placed orders with store names. 
SELECT 
c.first_name,
c.last_name,
o.order_id,
s.store_name
FROM customers AS C
JOIN orders AS o
ON o.customer_id = c.customer_id
JOIN stores AS s
ON s.store_id = o.store_id;


-- 4. Brand Insights – Total number of products per brand. 
SELECT 
b.brand_name,
COUNT(p.product_name) AS total_number_of_product_per_brand
FROM products AS p
JOIN brands AS b
ON b.brand_id = p.brand_id
GROUP BY b.brand_name
ORDER BY total_number_of_product_per_brand DESC;


-- 5. Low Stock Alert – Products with zero quantity in stock.
SELECT 
p.product_name,
s.quantity
FROM products AS p
JOIN stocks AS s
ON p.product_id = s.product_id
WHERE s.quantity = 0 OR NULL; 












 